#!/usr/bin/env bash
#First argument value is read by the variable $1 which will contain the filename for reading

FILE=$1

# If the file exists in the current location then while loop will read the file line by line

while read NUMBERS;
do
    factors=($(factor $NUMBERS))
    echo "$NUMBERS=$(($NUMBERS/${factors[1]}))*${factors[1]}"
done < $FILE
	
